### ISSUE TITLE
Inconsistent use of key

### ISSUE THREAD

**Issue by Alex-Yarkosky** [aubreypc/cs203-S2019-conduct#22] opened 2019-01-29 21:20 UTC
Under the `Conduct` section, the `Acceptable Conduct` subsection uses `(A)` when it should be using `(C)` to stay consistent with the key and the rest of the conduct guide. Please look into making this simple change to maintain a professional appearance.

**Comment by quigley-c** [comment] 2019-01-29 21:35
Duplicate of #21 ?

**Closed** 2019-01-29 21:36 UTC
